<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

In [2]:
import numpy as np

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [2]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"] #py or np are added to show python or numpy and variables dont need to have them
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [3]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [1]:
superhero_info = {
    "Natasha Romanoff": "Black Widow", #dictionary can hold two data together unlike lists or array
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

## 1.2 Accessing data from a list (or array)

In [8]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

py_real_names[0] #remember that indexing starts from 0 and not 1

'Natasha Romanoff'

In [10]:
py_super_names[0]

'Black Widow'

In [4]:
py_real_names[2]


'Stephen Strange'

In [12]:
py_super_names[2]    # Forward indexing 
                     # We need to know the size 
                     # beforehand for this to work.

'Doctor Strange'

In [5]:
py_super_names[-1] #negative value will return the last entry in the list so do not need to know how many elements are there


'Doctor Strange'

In [7]:
py_super_names[-2] #seems like this would just give the second entry in the list from the back

'Iron Man'

## 1.3 Accessing data from a dictionary

In [7]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}          #dictionary has key-value structure (key on left side, value on right) 

In [16]:
superhero_info["Natasha Romanoff"]

'Black Widow'

In [17]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [11]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

In [13]:
fruit_color = {"Apple": "Red", "Banana": "Yellow", "Peach": "Pink"}

In [14]:
fruit_color.keys()

dict_keys(['Apple', 'Banana', 'Peach'])

In [9]:
superhero_info.items() #returns the data of the key-value as a tuple

dict_items([('Natasha Romanoff', 'Black Widow'), ('Tony Stark', 'Iron Man'), ('Stephen Strange', 'Doctor Strange')])

In [20]:
heroes = superhero_info.items()
print("Original heroes:", heroes)
del[heroes["Natasha Romanoff"]]
print("Updated heroes:", heroes)

Original heroes: dict_items([('Natasha Romanoff', 'Black Widow'), ('Stephen Strange', 'Doctor Strange')])


TypeError: 'dict_items' object does not support item deletion

In [27]:
# random sales dictionary
sales = { 'apple': 2, 'orange': 3, 'grapes': 4 }

items = sales.items()

print('Original items:', items)

# delete an item from dictionary
del[sales["apple"]]

print('Updated items:', items)

Original items: dict_items([('apple', 2), ('orange', 3), ('grapes', 4)])
Updated items: dict_items([('orange', 3), ('grapes', 4)])


In [22]:
superhero_number = {
    "Natasha Romanoff": 1,
    "Tony Stark": 2,
    "Stephen Strange": 3
}          

In [28]:
heroesn = superhero_number.items()
print("Original heroes number:", heroesn)
del[heroesn["Tony Stark"]]
print("Updated heroes number:", heroesn)

Original heroes number: dict_items([('Natasha Romanoff', 1), ('Tony Stark', 2), ('Stephen Strange', 3)])


TypeError: 'dict_items' object does not support item deletion

## 1.4 Higher dimensional lists

In [15]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']] #example of 2D lists so do not need to have two seperate lists

In [16]:
fruit_info = [["Apple", "Red"],["Banana", "Yellow"],["Peach", "Pink"]]

In [19]:
fruit_info[1]

['Banana', 'Yellow']

# 2 Lists vs. Arrays

## 2.1 Size

In [25]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [26]:
len(py_list_2d)

10

In [27]:
len(np_array_2d)

10

In [28]:
np_array_2d.shape #shape is not a function

(10, 2)

## 2.2 Arrays are fussy about type

In [30]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [31]:
py_list #lists can accomodate more data types than array

[1, 1.5, 'A']

In [33]:
np_array #numbers turned to english, as only tolerate one type

array(['1', '1.5', 'A'], dtype='<U32')

In [3]:
list = [1,1.5]
np_array = np.array(list)

In [5]:
np_array #seems like the integer is changed to float instead

array([1. , 1.5])

## 2.3 Adding a number

In [44]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [48]:
py_list + 10        # Won't work! #The + operator for lists is used for concatenation, not for adding a constant to each element of the list

TypeError: can only concatenate list (not "int") to list

In [42]:
np_array + 10

array([11, 12, 13, 14, 15])

In [38]:
np_array + 6787989

array([6787990, 6787991, 6787992, 6787993, 6787994])

## 2.4 Adding another list

In [90]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [95]:
py_list_1 + py_list_2 #this works compared to adding an integer

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [96]:
np_array_1 + np_array_2 #addition of elements instead

array([11, 22, 33, 44, 55])

In [93]:
py_list_3 = [1, 2, 3, 4, 5,"s"]
py_list_4 = [10, 20, 30, 40, 50]

np_array_3 = np.array(py_list_3)
np_array_4 = np.array(py_list_4)

In [94]:
py_list_3 + py_list_4

[1, 2, 3, 4, 5, 's', 10, 20, 30, 40, 50]

In [98]:
np_array_3 + np_array_4 #does not work any more due to the string s

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U11'), dtype('int32')) -> None

## 2.5 Multiplying by a Number

In [99]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [101]:
py_list*2 #instead of multiplying by 2, the list is duplicated

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [102]:
py_list*4

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [104]:
np_array*2 #multiplies

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [105]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [106]:
py_list**2                      # Won't work!   #not mathematical 

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [107]:
np_array**2

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [108]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [109]:
py_list == 3     # Works, but what IS the question?

False

In [112]:
py_list == py_list #checks whether lists are equal


True

In [114]:
np_array == 3  #checks individual elements

array([False, False,  True, False, False])

In [115]:
np_array == 5

array([False, False, False, False,  True])

In [116]:
py_list > 3      # Won't work!

TypeError: '>' not supported between instances of 'list' and 'int'

In [117]:
np_array > 3  

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [126]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)  

In [127]:
sum(py_list)     # sum() is a base Python function

15

In [128]:
np_array.sum()

15

In [129]:
max(py_list)     # max() is a base Python function
#returns largest value

5

In [130]:
np_array.max()

5

In [132]:
min(py_list)     # min() is a base Python function
#returns smallest value

1

In [133]:
np_array.min()

1

In [135]:
py_list.sum()   # Won't work! #cannot sum a list

AttributeError: 'list' object has no attribute 'sum'

In [136]:
np_array.mean()

3.0

In [138]:
np_array.std()

1.4142135623730951

In [141]:
py_list.mean() #likewise cannot get mean and std from list
#operation on list works on whole list while on array works on individual elements

AttributeError: 'list' object has no attribute 'mean'

# Exercises & Self-Assessment

In [142]:
py_list = [1, 50, 3, 4, 5]
np_array = np.array(py_list)  

In [145]:
max(py_list) # double checked whether max is last element or max value

50

## Footnotes